import React, { Component } from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';


export class Calories extends Component {

// It's a data format example.
    state = {
        value: 0,
        listEat: []
    }

    OnInsertRow = (row) => {
        var list = this.state.listEat.slice();
        list.push({Name: row.Name, Calories: row.Calories});

        for(var i = 0; i < list.length; i++)
        {
            list[i].id = i;
        }
        this.setState({listEat: list});
    }

    OnAfterDeleteRow = (row) => {
        var list = this.state.listEat.slice();

        for (var i = row.length - 1; i >= 0; i--)
        {
            list.splice(row[i],1);
        }

        for(var i = 0; i < list.length; i++)
        {
            list[i].id = i;
        }

        this.setState({listEat: list});
    }

    render() 
    {
        var products = [{Name: "กระเพาะปลา	1 ชาม	", Calories: 150  },
                        {Name: "กระเพาะปลาตุ๋นน้ำแดง	1 ชาม	", Calories: 225  },
                        {Name: "กล้วยไข่	1 ลูก	", Calories: 40  },
                        {Name: "กล้วยคลุกมะพร้าว	1 ถ้วย	", Calories: 100  },
                        {Name: "กล้วยฉาบ	1 ชิ้น	", Calories: 29  },
                        {Name: "กล้วยตาก	1 ผล	", Calories: 30  },
                        {Name: "กล้วยทอด (กล้วยแขก)	1 ชิ้น	", Calories: 50  },
                        {Name: "กล้วยน้ำว้า	1 ลูก	", Calories: 36  },
                        {Name: "กล้วยบวชชี	1 ถ้วยเล็ก	", Calories: 152  },
                        {Name: "กล้วยเล็บมือนาง	1 ผล	", Calories: 30  },
                        {Name: "กล้วยหอม	1 ลูก	", Calories: 77  },
                        {Name: "ก๋วยจั๊บ	1 ชาม	", Calories: 240  },
                        {Name: "ก๋วยจั๊บญวณ	1 ชาม	", Calories: 235  },
                        {Name: "ก๋วยเตี๋ยวแขก	1 ชาม	", Calories: 380  },
                        {Name: "ก๋วยเตี๋ยวคั่วไก่	1 จาน	", Calories: 435  },
                        {Name: "ก๋วยเตี๋ยวต้มยำกุ้ง	1 ถ้วย	", Calories: 320  },
                        {Name: "ก๋วยเตี๋ยวเนื้อเรียง	1 ถ้วย	", Calories: 370  },
                        {Name: "ก๋วยเตี๋ยวเนื้อสับ	1 จาน	", Calories: 370  },
                        {Name: "ก๋วยเตี๋ยวผัดกะเพราไก่	1 จาน	", Calories: 440  },
                        {Name: "ก๋วยเตี๋ยวผัดไทยใส่ไข่	1 จาน	", Calories: 577  },
                        {Name: "ก๋วยเตี๋ยวราดหน้าปลากระพง	1 จาน	", Calories: 435  },
                        {Name: "ก๋วยเตี๋ยวเรือน้ำตก	1 ชาม	", Calories: 180  },
                        {Name: "ก๋วยเตี๋ยวเรือน้ำตกแห้ง	1 ชาม	", Calories: 225  },
                        {Name: "ก๋วยเตี๋ยวเส้นปลาน้ำ	1 ชาม	", Calories: 375  },
                        {Name: "ก๋วยเตี๋ยวเส้นปลาแห้ง	1 ชาม	", Calories: 420  },
                        {Name: "ก๋วยเตี๋ยวเส้นเล็กต้มยำหมู	1 ชาม	", Calories: 335  },
                        {Name: "ก๋วยเตี๋ยวเส้นเล็กหมูแห้ง	1 ชาม	", Calories: 330  },
                        {Name: "ก๋วยเตี๋ยวเส้นหมี่น้ำลูกชิ้นเนื้อวัว	1 จาน	", Calories: 226  },
                        {Name: "ก๋วยเตี๋ยวเส้นหมี่ลูกชิ้นเนื้อ	1 ชาม	", Calories: 258  },
                        {Name: "ก๋วยเตี๋ยวเส้นใหญ่ผัดซีอิ๊วใส่ไข่	1 จาน	", Calories: 520  },
                        {Name: "ก๋วยเตี๋ยวเส้นใหญ่ราดหน้าไก่	1 จาน	", Calories: 397  },
                        {Name: "ก๋วยเตี๋ยวเส้นใหญ่ราดหน้าหมู	1 จาน	", Calories: 397  },
                        {Name: "ก๋วยเตี๋ยวหลอด	1 ชิ้น	", Calories: 50  },
                        {Name: "กะละแม	1 ห่อเล็ก	", Calories: 65  },
                        {Name: "กะหรี่พัฟ	1 ตัว	", Calories: 157  },
                        {Name: "กุ้งแช่น้ำปลา	1 ตัว	", Calories: 14  },
                        {Name: "กุ้งทอดกระเทียมพริกไทย	1 ตัวกลาง	", Calories: 86  },
                        {Name: "กุ้งนางนึ่งนมสด	1 ถ้วย	", Calories: 185  },
                        {Name: "กุ้งนึ่งกระเทียม	1 จาน	", Calories: 124  },
                        {Name: "กุ้งผัดพริกอ่อน	1 จาน	", Calories: 235  },
                        {Name: "กุ้งฝอยชุบแป้งทอด	1 แพ	", Calories: 308  },
                        {Name: "กุ้งอบวุ้นเส้น	1 จาน	", Calories: 300  },
                        {Name: "กุนเชียงทอด	1 ชิ้นเล็ก	", Calories: 120  },
                        {Name: "กุ้ยช่ายทอด	1 ชิ้น	", Calories: 114  },
                        {Name: "เกาเหลาราดหน้า	1 ถ้วย	", Calories: 300  },
                        {Name: "เกาเหลาลูกชิ้นน้ำ	1 ชาม	", Calories: 225  },
                        {Name: "เกี๊ยวกรอบราดหน้ากุ้ง	1 จาน	", Calories: 635  },
                        {Name: "เกี๊ยวซ่า	1 ชิ้น	", Calories: 63  },
                        {Name: "เกี๊ยวน้ำกุ้ง	1 ชาม	", Calories: 275  },
                        {Name: "เกี๊ยวปลาน้ำ	1 ถ้วย	", Calories: 165  },
                        {Name: "แกงกะหรี่ไก่	1 ถ้วย	", Calories: 450  },
                        {Name: "แกงกะหรี่หมู	1 ถ้วย	", Calories: 325  },
                        {Name: "แกงขี้เหล็ก	1 ถ้วย	", Calories: 195  },
                        {Name: "แกงขี้เหล็กหมูย่าง	1 ถ้วย	", Calories: 245  },
                        {Name: "แกงเขียวหวานไก่	1 ถ้วย	", Calories: 240  },
                        {Name: "แกงเขียวหวานปลาดุก	1 ถ้วย	", Calories: 235  },
                        {Name: "แกงเขียวหวานลูกชิ้นปลากราย	1 ถ้วย	", Calories: 240  },
                        {Name: "แกงเขียวหวานหมู	1 ถ้วย	", Calories: 235  },
                        {Name: "แกงจืดไข่เจียว	1 ถ้วย	", Calories: 120  },
                        {Name: "แกงจืดตำลึงหมูสับ	1 ถ้วย	", Calories: 90  },
                        {Name: "แกงจืดเต้าหู้ไม่ใส่หมูสับ	1 ถ้วย	", Calories: 80  },
                        {Name: "แกงจืดเต้าหู้ยัดไส้	1 ถ้วย	", Calories: 110  },
                        {Name: "แกงจืดถั่วงอกไม่ใส่หมูสับ	1 ถ้วย	", Calories: 50  },
                        {Name: "แกงจืดถั่วงอกหมูสับ	1 ถ้วย	", Calories: 50  },
                        {Name: "แกงจืดฟักยัดไส้	1 ถ้วย	", Calories: 90  },
                        {Name: "แกงจืดมะระยัดไส้	1 ถ้วย	", Calories: 90  },
                        {Name: "แกงจืดมะระสอดไส้หมูวุ้นเส้น	1 ชิ้น	", Calories: 66  },
                        {Name: "แกงจืดวุ้นเส้น	1 ถ้วย	", Calories: 85  },
                        {Name: "แกงไตปลา	1 ถ้วย	", Calories: 50  },
                        {Name: "แกงป่าไก่	1 ถ้วย	", Calories: 110  },
                        {Name: "แกงเผ็ดไก่ใส่มะเขือ	1 ถ้วย	", Calories: 235  },
                        {Name: "แกงเผ็ดไก่ใส่หน่อไม้	1 ถ้วย	", Calories: 245  },
                        {Name: "แกงเผ็ดเป็ดย่าง	1 ถ้วย	", Calories: 240  },
                        {Name: "แกงเผ็ดฟักทองใส่หมู	1 ถ้วย	", Calories: 250  },
                        {Name: "แกงเผ็ดฟักทองหมู	1 ถ้วย	", Calories: 250  },
                        {Name: "แกงเผ็ดมะเขือไก่	1 ถ้วย	", Calories: 235  },
                        {Name: "แกงเผ็ดลูกชิ้นปลา	1 ถ้วย	", Calories: 240  },
                        {Name: "แกงเผ็ดหน่อไม้ไก่	1 ถ้วย	", Calories: 245  },
                        {Name: "แกงเผ็ดหมูยอดมะพร้าว	1 ถ้วย	", Calories: 245  },
                        {Name: "แกงมัสมั่นไก่	1 ถ้วย	", Calories: 325  },
                        {Name: "แกงเลียง	1 ชาม	", Calories: 115  },
                        {Name: "แกงเลียงผักรวม	1 ถ้วย	", Calories: 48  },
                        {Name: "แกงส้ม	1 ถ้วย	", Calories: 28  },
                        {Name: "แกงส้มชะอมไข่ทอดใส่กุ้ง	1 ถ้วย	", Calories: 270  },
                        {Name: "แกงส้มดอกแคกุ้ง	1 ถ้วย	", Calories: 105  },
                        {Name: "แกงส้มปลาช่อนผักบุ้ง	1 ถ้วย	", Calories: 105  },
                        {Name: "แกงส้มปลาแปะซะ	1 ถ้วย	", Calories: 160  },
                        {Name: "แกงส้มผักกะเฉด-ปลา	1 ชาม	", Calories: 110  },
                        {Name: "แกงส้มผักบุ้งปลาช่อน	1 ถ้วย	", Calories: 105  },
                        {Name: "แกงส้มผักรวม	1 ถ้วย	", Calories: 120  },
                        {Name: "แกงหมูเทโพ	1 ถ้วย	", Calories: 300  },
                        {Name: "แกงเหลืองมะละกอกุ้ง	1 ถ้วย	", Calories: 80  },
                        {Name: "แกงเหลืองหน่อไม้ดองกับปลา	1 ถ้วย	", Calories: 80  },
                        {Name: "แก้วมังกร	1 ลูก	", Calories: 60  },
                        {Name: "โกยซีหมี่	1 จาน	", Calories: 550  },
                        {Name: "ไก่ KFC สะโพก	1 ชิ้น	", Calories: 355  },
                        {Name: "ไก่ KFC ฮอทวิงส์	1 ชิ้น	", Calories: 78  },
                        {Name: "ไก่ตุ๋นมะนาวดอง	1 ชาม	", Calories: 110  },
                        {Name: "ไก่ทอด	1 น่อง	", Calories: 345  },
                        {Name: "ไก่ผัดขิง	1 จาน	", Calories: 210  },
                        {Name: "ไก่ยอชุบแป้งทอด	1 ชิ้น	", Calories: 73  },
                        {Name: "ไก่ย่าง	1 น่อง	", Calories: 165  },
                        {Name: "ขนมกรวย	1 กรวย	", Calories: 63  },
                        {Name: "ขนมกล้วย	1 ห่อ	", Calories: 120  },
                        {Name: "ขนมกลีบลำดวน	1 ชิ้น	", Calories: 23  },
                        {Name: "ขนมกุ้ยช่าย	1 ชิ้น	", Calories: 53  },
                        {Name: "ขนมเกลียว	1 ตัว	", Calories: 25  },
                        {Name: "ขนมขี้หนู	1 ถ้วย	", Calories: 165  },
                        {Name: "ขนมเข่ง	1 กระทง	", Calories: 120  },
                        {Name: "ขนมครก	1 คู่	", Calories: 92  },
                        {Name: "ขนมจีน	1 ทัพพี	", Calories: 80  },
                        {Name: "ขนมจีนแกงเขียวหวานไก่	1 ชาม	", Calories: 594  },
                        {Name: "ขนมจีนซาวน้ำ	1 จาน	", Calories: 320  },
                        {Name: "ขนมจีนน้ำเงี้ยว	1 ถ้วย	", Calories: 243  },
                        {Name: "ขนมจีนน้ำพริก	1 จาน	", Calories: 228  },
                        {Name: "ขนมจีนน้ำยา	1 จาน	", Calories: 332  },
                        {Name: "ขนมจีนน้ำยาปักษ์ใต้	1 จาน	", Calories: 146  },
                        {Name: "ขนมจีบหมู	1 ชิ้น	", Calories: 32  },
                        {Name: "ขนมตาล	1 กระทง	", Calories: 58  },
                        {Name: "ขนมถั่วแปป	1 ชิ้น	", Calories: 14  },
                        {Name: "ขนมเทียน	1 ห่อ	", Calories: 103  },
                        {Name: "ขนมบ้าบิ่น	1 ชิ้น	", Calories: 130  },
                        {Name: "ขนมเบื้องไทยไส้เค็ม	1 แผ่น	", Calories: 50  },
                        {Name: "ขนมเบื้องไทยไส้หวาน	1 แผ่น	", Calories: 60  },
                        {Name: "ขนมเปียกปูน	1 จานเล็ก	", Calories: 195  },
                        {Name: "ขนมผิง	1 ก้อนเล็ก	", Calories: 5  },
                        {Name: "ขนมฝักบัว	1 ชิ้น	", Calories: 70  },
                        {Name: "ขนมเล็บมือนาง	1 จานเล็ก	", Calories: 275  },
                        {Name: "ขนมหน้านวล	1 ชิ้น	", Calories: 22  },
                        {Name: "ขนมหัวผักกาดผัด	1 จาน	", Calories: 560  },
                        {Name: "ขนมหัวผักกาดผัดใส่ไข่	1 จาน	", Calories: 630  },
                        {Name: "ข้าวกะเพราเนื้อ	1 จาน	", Calories: 622  },
                        {Name: "ข้าวกุ้งทอดกระเทียม	1 จาน	", Calories: 495  },
                        {Name: "ข้าวเกรียบกุ้ง	1 แผ่น	", Calories: 37  },
                        {Name: "ข้าวเกรียบปากหม้อ	1 ชิ้น	", Calories: 26  },
                        {Name: "ข้าวแกงกะหรี่ไก่	1 จาน	", Calories: 389  },
                        {Name: "ข้าวแกงเผ็ดไก่	1 จาน	", Calories: 485  },
                        {Name: "ข้าวไก่อบ	1 จาน	", Calories: 490  },
                        {Name: "ข้าวขาหมู	1 จาน	", Calories: 690  },
                        {Name: "ข้าวไข่เจียว	1 จาน	", Calories: 445  },
                        {Name: "ข้าวคลุกกะปิ	1 จาน	", Calories: 410  },
                        {Name: "ข้าวแช่	1 ชุด	", Calories: 350  },
                        {Name: "ข้าวซอยไก่	1 ชาม	", Calories: 395  },
                        {Name: "ข้าวซอยหมู	1 ชาม	", Calories: 395  },
                        {Name: "ข้าวต้ม (ข้าวกล้อง)	1 ถ้วย	", Calories: 120  },
                        {Name: "ข้าวต้ม (ข้าวขาว)	1 ถ้วย	", Calories: 120  },
                        {Name: "ข้าวต้มทรงเครื่อง	1 ถ้วย	", Calories: 230  },
                        {Name: "ข้าวต้มปลา	1 ถ้วย	", Calories: 325  },
                        {Name: "ข้าวต้มมัด	1 มัด	", Calories: 285  },
                        {Name: "ข้าวตังหน้าตั้ง	1 แผ่น	", Calories: 90  },
                        {Name: "ข้าวตังหมูหยอง	1 แผ่น	", Calories: 80  },
                        {Name: "ข้าวแตนราดน้ำตาล	1 แผ่น	", Calories: 150  },
                        {Name: "ข้าวปุ้น(ส้มตำ-ขนมจีน)	1 จาน	", Calories: 180  },
                        {Name: "ข้าวผัดกระเพราหมูกรอบ	1 จาน	", Calories: 650  },
                        {Name: "ข้าวผัดกะเพรากุ้ง	1 จาน	", Calories: 540  },
                        {Name: "ข้าวผัดกะเพราไก่	1 จาน	", Calories: 554  },
                        {Name: "ข้าวผัดกะเพราไก่ไข่ดาว	1 จาน	", Calories: 630  },
                        {Name: "ข้าวผัดกะเพราหมู	1 จาน	", Calories: 580  },
                        {Name: "ข้าวผัดกุ้งใส่ไข่	1 จาน	", Calories: 595  },
                        {Name: "ข้าวผัดกุนเชียง	1 จาน	", Calories: 590  },
                        {Name: "ข้าวผัดแกงเขียวหวานไก่	1 จาน	", Calories: 630  },
                        {Name: "ข้าวผัดคะน้าหมูกรอบ	1 จาน	", Calories: 670  },
                        {Name: "ข้าวผัดต้มยำทะเลแห้ง	1 จาน	", Calories: 400  },
                        {Name: "ข้าวผัดน้ำพริกกุ้งสด	1 จาน	", Calories: 460  },
                        {Name: "ข้าวผัดน้ำพริกเผาหมู	1 จาน	", Calories: 665  },
                        {Name: "ข้าวผัดน้ำพริกลงเรือ	1 จาน	", Calories: 605  },
                        {Name: "ข้าวผัดปลาเค็ม	1 จาน	", Calories: 405  },
                        {Name: "ข้าวผัดปลาหมึกน้ำพริกเผา	1 จาน	", Calories: 535  },
                        {Name: "ข้าวผัดปูใส่ไข่	1 จาน	", Calories: 610  },
                        {Name: "ข้าวผัดผักกระเฉดหมูกรอบ	1 จาน	", Calories: 600  },
                        {Name: "ข้าวผัดมันกุ้งใส่ไข่	1 จาน	", Calories: 575  },
                        {Name: "ข้าวผัดรวมมิตร (น้ำมันน้อย)	1 จาน	", Calories: 210  },
                        {Name: "ข้าวผัดสับปะรด	1 จาน	", Calories: 335  },
                        {Name: "ข้าวผัดไส้กรอก	1 จาน	", Calories: 520  },
                        {Name: "ข้าวผัดหนำเลียบหมูใส่ไข่	1 จาน	", Calories: 370  },
                        {Name: "ข้าวผัดหมูน้ำพริกเผา	1 จาน	", Calories: 665  },
                        {Name: "ข้าวผัดหมูใส่ไข่	1 จาน	", Calories: 557  },
                        {Name: "ข้าวผัดแหนม	1 จาน	", Calories: 610  },
                        {Name: "ข้าวผัดอเมริกัน	1 จาน	", Calories: 790  },
                        {Name: "ข้าวพะแนงเนื้อ	1 จาน	", Calories: 457  },
                        {Name: "ข้าวโพดต้ม	1 ฝัก	", Calories: 200  },
                        {Name: "ข้าวมันไก่	1 จาน	", Calories: 596  },
                        {Name: "ข้าวมันไก่ทอด	1 จาน	", Calories: 695  },
                        {Name: "ข้าวเม่าทอด	1 ชิ้น	", Calories: 209  },
                        {Name: "ข้าวยำปักษ์ใต้	1 จาน	", Calories: 248  },
                        {Name: "ข้าวราดแกงเขียวหวานไก่	1 จาน	", Calories: 483  },
                        {Name: "ข้าวราดผัดผักบุ้ง ไข่ดาว	1 จาน	", Calories: 410  },
                        {Name: "ข้าวราดผัดผักใส่หมู	1 จาน	", Calories: 370  },
                        {Name: "ข้าวราดหน้าไก่	1 จาน	", Calories: 400  },
                        {Name: "ข้าวสตูว์ไก่	1 จาน	", Calories: 465  },
                        {Name: "ข้าวสวย	1 ทัพพี	", Calories: 68  },
                        {Name: "ข้าวสวย (ข้าวกล้อง)	1 ทัพพี	", Calories: 80  },
                        {Name: "ข้าวสวย (ข้าวขาว)	1 ทัพพี	", Calories: 80  },
                        {Name: "ข้าวหน้ากุ้งผัดพริดสด	1 จาน	", Calories: 540  },
                        {Name: "ข้าวหน้าเป็ด	1 จาน	", Calories: 495  },
                        {Name: "ข้าวหมกไก่	1 จาน	", Calories: 534  },
                        {Name: "ข้าวหมูแดง	1 จาน	", Calories: 541  },
                        {Name: "ข้าวหมูทอด	1 จาน	", Calories: 416  },
                        {Name: "ข้าวหมูทอดกระเทียม	1 จาน	", Calories: 525  },
                        {Name: "ข้าวหมูอบ	1 จาน	", Calories: 389  },
                        {Name: "ข้าวเหนียวกะทิทุเรียน	1 ถ้วย	", Calories: 225  },
                        {Name: "ข้าวเหนียวดำ	1 ถ้วยเล็ก	", Calories: 205  },
                        {Name: "ข้าวเหนียวตัด	1 ชิ้น	", Calories: 210  },
                        {Name: "ข้าวเหนียวนึ่ง	1 ทัพพี	", Calories: 160  },
                        {Name: "ข้าวเหนียวมูลกะทิ	1 จานเล็ก	", Calories: 197  },
                        {Name: "ข้าวเหนียวหน้าสังขยา	1 จานเล็ก	", Calories: 223  },
                        {Name: "ข้าวเหนียวหมูทอด	1 ชุด	", Calories: 440  },
                        {Name: "ข้าวเหนียวหมูสวรรค์	1 ชุด	", Calories: 480  },
                        {Name: "ข้าวอบเผือก	1 จาน	", Calories: 385  },
                        {Name: "ไข่เค็ม	1 ฟอง	", Calories: 75  },
                        {Name: "ไข่เจียว	1 ฟอง	", Calories: 215  },
                        {Name: "ไข่ดาว	1 ฟอง	", Calories: 215  },
                        {Name: "ไข่ดาวทรงเครื่อง	1 ฟอง	", Calories: 250  },
                        {Name: "ไข่ต้ม	1 ฟอง	", Calories: 73  },
                        {Name: "ไข่ตุ๋น	1 ฟอง	", Calories: 75  },
                        {Name: "ไข่ตุ๋นทรงเครื่อง	1 ฟอง	", Calories: 159  },
                        {Name: "ไข่นกกระทา	1 จานเล็ก	", Calories: 191  },
                        {Name: "ไข่พะโล้	1 ถ้วย	", Calories: 180  },
                        {Name: "ไข่ยัดไส้	1 จาน	", Calories: 310  },
                        {Name: "ไข่ลวก	1 ฟอง	", Calories: 75  },
                        {Name: "ไข่ลูกเขย	1 ฟอง	", Calories: 205  },
                        {Name: "ไข่หงส์	1 ใบ	", Calories: 58  },
                        {Name: "ครองแครงกรอบเค็ม	1 ตัว	", Calories: 19  },
                        {Name: "ครัวซอง	1 ชิ้น	", Calories: 235  },
                        {Name: "ครีมซุปไก่	1 ถ้วย	", Calories: 160  },
                        {Name: "คอหมูย่าง	1 จาน	", Calories: 200  },
                        {Name: "คะน้าหมูกรอบ	1 จาน	", Calories: 420  },
                        {Name: "เครื่องในไก่ผัดขิง	1 จาน	", Calories: 200 },
                        {Name: "แคนตาลูป	1 ชิ้น	", Calories: 4  },
                        {Name: "แคบหมู มีมัน	1 ชิ้นเล็ก	", Calories: 13  },
                        {Name: "แคบหมู ไร้มัน	1 ชิ้นเล็ก	", Calories: 10  },
                        {Name: "โครงไก่ทอด	1 ตัว	", Calories: 656 },
                        {Name: "เงาะ	1 ลูก	", Calories: 12 },
                        {Name: "แจ่วบอง	1 ถ้วย	", Calories: 25  },
                        {Name: "โจ๊กใส่ไข่	1 ถ้วย	", Calories: 250  },
                        {Name: "โจ๊กหมู	1 ถ้วย	", Calories: 160  },
                        {Name: "โจ๊กหมูตับ ใส่ไข่ลวก	1 ถ้วย	", Calories: 230 },
                        {Name: "เฉาก๊วย	1 ถ้วย	", Calories: 90  },
                        {Name: "ชมพู่	1 ผล	", Calories: 16  },
                        {Name: "เชอรี่	1 ผล	", Calories: 15  },
                        {Name: "ซาลาเปาทอด	1 ลูก	", Calories: 157  },
                        {Name: "ซาลาเปาไส้หมู	1 ลูก	", Calories: 202  },
                        {Name: "ซาหริ่ม	1 ชุด	", Calories: 217  },
                        {Name: "ซ่าหริ่ม	1 ถ้วย	", Calories: 275  },
                        {Name: "ซุปข้าวโพด	1 ถ้วย	", Calories: 140  },
                        {Name: "ซุปผัก (ใส)	1 ถ้วย	", Calories: 15  },
                        {Name: "ซุปหน่อไม้	1 จาน	", Calories: 40  },
                        {Name: "ต้มกะทิสายบัวปลาทูนึ่ง	1 ถ้วย	", Calories: 225  },
                        {Name: "ต้มข่าไก่	1 ถ้วย	", Calories: 210  },
                        {Name: "ต้มโคล้งไก่ย่าง	1 ถ้วย	", Calories: 115  },
                        {Name: "ต้มโคล้งปลากรอบ	1 ถ้วย	", Calories: 60  },
                        {Name: "ต้มจับฉ่าย	1 ถ้วย	", Calories: 15  },
                        {Name: "ต้มจืดเลือดหมู	1 ถ้วย	", Calories: 120  },
                        {Name: "ต้มตือฮวน	1 ถ้วย	", Calories: 160  },
                        {Name: "ต้มผักกาดดองซี่โครงหมู	1 ถ้วย	", Calories: 90  },
                        {Name: "ต้มยำกุ้ง	1 ถ้วย	", Calories: 65  },
                        {Name: "ต้มยำไก่	1 ถ้วย	", Calories: 60  },
                        {Name: "ต้มยำไก่ใส่เห็ด	1 ถ้วย	", Calories: 80  },
                        {Name: "ต้มยำปลากระป๋อง	1 ถ้วย	", Calories: 55  },
                        {Name: "ต้มยำปลากระพง	1 ถ้วย	", Calories: 80  },
                        {Name: "ต้มยำปลาทู	1 ถ้วย	", Calories: 10  },
                        {Name: "ต้มยำปลาหมึก	1 ถ้วย	", Calories: 9  },
                        {Name: "ต้มยำเห็ดสด	1 ถ้วย	", Calories: 30  },
                        {Name: "ต้มส้มปลาทู	1 ถ้วย	", Calories: 130  },
                        {Name: "ต้มหัวผักกาดขาวซี่โครงหมู	1 ถ้วย	", Calories: 90  },
                        {Name: "ตะโก้แห้ว	1 กระทง	", Calories: 78  },
                        {Name: "ตับไก่ปิ้ง	1 ไม้	", Calories: 60  },
                        {Name: "เต้าส่วน	1 ถ้วย	", Calories: 215  },
                        {Name: "เต้าหู้แข็ง	1 ก้อน	", Calories: 210  },
                        {Name: "เต้าหู้ไข่	1 หลอด	", Calories: 70  },
                        {Name: "เต้าหู้ทอด	1 ชิ้น	", Calories: 57  },
                        {Name: "เต้าหู้นมสด	1 ถ้วย	", Calories: 150  },
                        {Name: "เต้าฮวยน้ำขิง	1 ถ้วย	", Calories: 130  },
                        {Name: "แตงไทย	1 ชิ้น	", Calories: 4  },
                        {Name: "แตงโม	1 กิโลกรัม	", Calories: 250  },
                        {Name: "ถั่วทอด	1 แพ	", Calories: 82  },
                        {Name: "ถั่วลิสงทอด	1 ช้อนโต๊ะ	", Calories: 62  },
                        {Name: "ทองม้วน	1 อัน	", Calories: 35  },
                        {Name: "ทอดมันกุ้ง	1 จาน	", Calories: 255  },
                        {Name: "ทอดมันปลากลาย	1 ชิ้น	", Calories: 37  },
                        {Name: "ทับทิมกรอบ	1 ถ้วย	", Calories: 250  },
                        {Name: "ทุเรียน	1 เม็ด	", Calories: 59  },
                        {Name: "ทุเรียนทอดกรอบ	1 ชิ้น	", Calories: 9  },
                        {Name: "เทมปุระ	1 ชิ้น	", Calories: 77  },
                        {Name: "นมถั่วเหลือง (ไม่มีน้ำตาล)	1 แก้ว	", Calories: 55  },
                        {Name: "น่องไก่ทอด	1 ชิ้น	", Calories: 345  },
                        {Name: "น่องไก่ย่าง	1 น่อง	", Calories: 97  },
                        {Name: "น้อยหน่า	1 ลูก	", Calories: 61  },
                        {Name: "น้ำกระเจี๊ยบ	1 แก้ว	", Calories: 120  },
                        {Name: "น้ำโค้ก, น้ำเป๊ปซี่	1 แก้ว	", Calories: 100  },
                        {Name: "น้ำปลามะนาว	1 ตัวเล็ก	", Calories: 165  },
                        {Name: "น้ำพริกกะปิผักสด	1 ช้อนโต๊ะ	", Calories: 28  },
                        {Name: "น้ำพริกกุ้งเผา	1 ถ้วย	", Calories: 90  },
                        {Name: "น้ำพริกปลาป่น	1 ถ้วย	", Calories: 35  },
                        {Name: "น้ำพริกมะขามเปียก	1 ถ้วย	", Calories: 55  },
                        {Name: "น้ำพริกมะขามสด	1 ถ้วย	", Calories: 210  },
                        {Name: "น้ำพริกมะม่วง	1 ถ้วย	", Calories: 100  },
                        {Name: "น้ำพริกลงเรือ	1 ถ้วย	", Calories: 195  },
                        {Name: "น้ำพริกหนุ่ม	1 ช้อนโต๊ะ	", Calories: 18  },
                        {Name: "น้ำพริกอ่อง	1 ช้อนโต๊ะ	", Calories: 80 },
                        {Name: "น้ำมะเขือเทศ	1 แก้ว	", Calories: 48  },
                        {Name: "น้ำมะตูม	1 แก้ว	", Calories: 120  },
                        {Name: "น้ำมะนาว	1 แก้ว	", Calories: 100  },
                        {Name: "น้ำมะพร้าว	1 แก้ว	", Calories: 120  },
                        {Name: "น้ำลำใย	1 แก้ว	", Calories: 100  },
                        {Name: "น้ำส้มคั้น	1 แก้ว	", Calories: 160  },
                        {Name: "น้ำสับปะรด	1 แก้ว	", Calories: 125  },
                        {Name: "น้ำองุ่น	1 แก้ว	", Calories: 112  },
                        {Name: "น้ำอ้อย	1 แก้ว	", Calories: 240  },
                        {Name: "เนื้อไก่ชุปแป้งทอด	1 ชิ้นเล็ก	", Calories: 71  },
                        {Name: "เนื้อน้ำตก	1 จาน	", Calories: 165  },
                        {Name: "เนื้อผัดหวาน	1 จาน	", Calories: 590  },
                        {Name: "บรั่นดี	1 cc	", Calories: 2  },
                        {Name: "บะจ่าง	1 ลูก	", Calories: 300  },
                        {Name: "บะหมี่กรอบราดหน้า	1 จาน	", Calories: 515  },
                        {Name: "บะหมี่กรอบราดหน้าไก่หน่อไม้	1 จาน	", Calories: 660  },
                        {Name: "บะหมี่กรอบราดหน้ารวมมิตร	1 จาน	", Calories: 690  },
                        {Name: "บะหมี่กึ่งสำเร็จรูป	1 ก้อน	", Calories: 253  },
                        {Name: "บะหมี่กึ่งสำเร็จรูปผัดกระเพราหมู	1 จาน	", Calories: 540  },
                        {Name: "บะหมี่กึ่งสำเร็จรูปผัดขี้เมา	1 จาน	", Calories: 530  },
                        {Name: "บะหมี่เกี๊ยวเป็ดย่าง	1 ชาม	", Calories: 415  },
                        {Name: "บะหมี่น่องไก่-น้ำ	1 ชาม	", Calories: 375  },
                        {Name: "บะหมี่น้ำเกี๊ยวหมูแดง	1 ชาม	", Calories: 305  },
                        {Name: "บะหมี่น้ำต้มยำหมู	1 ถ้วย	", Calories: 300  },
                        {Name: "บะหมี่น้ำน่องไก่	1 ชาม	", Calories: 375  },
                        {Name: "บะหมี่น้ำเป็ด	1 ชาม	", Calories: 370  },
                        {Name: "บะหมี่น้ำหมูต้มยำ	1 ชาม	", Calories: 300  },
                        {Name: "บะหมี่หมูแดง	1 ชาม	", Calories: 231  },
                        {Name: "บะหมี่แห้งหมูแดง	1 ชาม	", Calories: 345  },
                        {Name: "บัวลอย	1 ถ้วยเล็ก	", Calories: 223  },
                        {Name: "บัวลอยเผือก	1 ถ้วย	", Calories: 300  },
                        {Name: "บาร์บีคิวซี่โครงหมูข้าวคลุกเนย	1 ชุด	", Calories: 340  },
                        {Name: "เบียร์ไทย	1 แก้ว	", Calories: 148  },
                        {Name: "ปลากระพงนึ่งมะนาว	1 ชิ้นกลาง	", Calories: 155  },
                        {Name: "ปลาช่อนทอด	1 ตัว	", Calories: 1840  },
                        {Name: "ปลาช่อนอบเกลือ	1 ตัว	", Calories: 220  },
                        {Name: "ปลาชุบขนมปังทอด + สลัดผัก	1 จาน	", Calories: 595  },
                        {Name: "ปลาซาบะย่าง	1 ตัว	", Calories: 220  },
                        {Name: "ปลาแซลมอนย่าง	1 จาน	", Calories: 260  },
                        {Name: "ปลาทอดสามรส	1 ตัวกลาง	", Calories: 470  },
                        {Name: "ปลาทูทอด	1 ตัวกลาง	", Calories: 280  },
                        {Name: "ปลานึ่ง	1 ตัว	", Calories: 156  },
                        {Name: "ปลาเผา	1 ตัว	", Calories: 156  },
                        {Name: "ปลาราดซอสมะนาวมันฝรั่งทอด	1 จาน	", Calories: 560  },
                        {Name: "ปลาราดพริก	1 จาน	", Calories: 300 },
                        {Name: "ปลาร้าทรงเครื่อง	1 ถ้วย	", Calories: 155  },
                        {Name: "ปลาร้าสับ	1 ถ้วย	", Calories: 35  },
                        {Name: "ปลาเล็กปลาน้อยทอดกรอบ	1 ช้อนโต๊ะ	", Calories: 80  },
                        {Name: "ปลาสลิดทอด	1 ตัว	", Calories: 190  },
                        {Name: "ปลาหมึกชุปแป้งทอด	1 ชิ้น	", Calories: 49  },
                        {Name: "ปลาหมึกนึ่งมะนาว	1 ตัว	", Calories: 75  },
                        {Name: "ปลาหมึกผัดฉ่า	1 ถ้วย	", Calories: 260  },
                        {Name: "ปลาหมึกย่าง	1 ไม้	", Calories: 37  },
                        {Name: "ปลาอินทรีย์เค็มทอด	1 จาน	", Calories: 115  },
                        {Name: "ปอเปี๊ยะทอด	1 ชิ้น	", Calories: 158  },
                        {Name: "ปาท่องโก๋	1 ตัว	", Calories: 124  },
                        {Name: "ปีกไก่ทอด	1 ชิ้นกลาง	", Calories: 107  },
                        {Name: "ปีกไก่สอดไส้ทอด	1 ชิ้น	", Calories: 103  },
                        {Name: "ปีกไก่อบ	1 ชิ้น	", Calories: 169  },
                        {Name: "เป็ดตุ๋นมะนาวดอง	1 ถ้วย	", Calories: 110  },
                        {Name: "เป็ดพะโล้	1 ถ้วย	", Calories: 110  },
                        {Name: "ผัดกะหล่ำปลีหมู	1 จาน	", Calories: 230  },
                        {Name: "ผัดกุ้งสะตอหมู	1 จาน	", Calories: 200  },
                        {Name: "ผัดกุ้งหน่อไม้ฝรั่ง	1 จาน	", Calories: 230  },
                        {Name: "ผัดไข่หน่อไม้	1 จาน	", Calories: 200  },
                        {Name: "ผัดคะน้าปลาเค็ม	1 จาน	", Calories: 200  },
                        {Name: "ผัดไชโป๊วใส่ไข่	1 จาน	", Calories: 125  },
                        {Name: "ผัดซีอิ๊วเส้นใหญ่หมูใส่ไข่	1 จาน	", Calories: 679  },
                        {Name: "ผัดดอกกะหล่ำกุ้ง	1 จาน	", Calories: 210  },
                        {Name: "ผัดดอกกุ่ยช่ายตับ	1 จาน	", Calories: 210  },
                        {Name: "ผัดถั่วงอกเต้าหู้	1 จาน	", Calories: 155  },
                        {Name: "ผัดถั่วลันเตากุ้ง	1 จาน	", Calories: 190 },
                        {Name: "ผัดไทยกุ้งสด	1 จาน	", Calories: 486  },
                        {Name: "ผัดไทยกุ้งสดใส่ไข่	1 จาน	", Calories: 545  },
                        {Name: "ผัดไทยไร้เส้น	1 จาน	", Calories: 182  },
                        {Name: "ผัดไทยวุ้นเส้นกุ้งสด	1 จาน	", Calories: 520  },
                        {Name: "ผัดไทยห่อไข่	1 จาน	", Calories: 565  },
                        {Name: "ผัดบร็อกโคลี่กุ้ง	1 จาน	", Calories: 210  },
                        {Name: "ผัดบวบใส่ไข่	1 จาน	", Calories: 210  },
                        {Name: "ผัดเปรี้ยวหวานไก่	1 จาน	", Calories: 215  },
                        {Name: "ผัดผักกระเฉดน้ำมันหอย	1 จาน	", Calories: 185  },
                        {Name: "ผัดผักกาดขาวหมูวุ้นเส้น	1 จาน	", Calories: 230  },
                        {Name: "ผัดผักกาดดองใส่ไข่	1 จาน	", Calories: 205  },
                        {Name: "ผัดผักคะน้าน้ำมันหอย	1 จาน	", Calories: 210  },
                        {Name: "ผัดผักบุ้ง (ไม่ใส่น้ำมัน)	1 จาน	", Calories: 40  },
                        {Name: "ผัดผักบุ้งไฟแดง	1 จาน	", Calories: 210  },
                        {Name: "ผัดผักรวมหมู	1 จาน	", Calories: 210  },
                        {Name: "ผัดเผ็ดปลาดุก	1 จาน	", Calories: 200  },
                        {Name: "ผัดเผ็ดปลาทอดกรอบ	1 จาน	", Calories: 290  },
                        {Name: "ผัดเผ็ดมะเขือหมู	1 จาน	", Calories: 250  },
                        {Name: "ผัดพริกแกงหมูหน่อไม้	1 จาน	", Calories: 200  },
                        {Name: "ผัดพริกขิงกุ้งกับถั่วฝักยาว	1 จาน	", Calories: 245  },
                        {Name: "ผัดพริกขิงหมูถั่วฝักยาว	1 จาน	", Calories: 265  },
                        {Name: "ผัดฟักทองใส่ไข่	1 จาน	", Calories: 255  },
                        {Name: "ผัดมะเขือยาวหมูสับ	1 จาน	", Calories: 210  },
                        {Name: "ผัดมักกะโรนีกุ้ง	1 จาน	", Calories: 420  },
                        {Name: "ผัดมักกะโรนีหมู	1 จาน	", Calories: 514  },
                        {Name: "ผัดยอดมะระน้ำมันหอย	1 จาน	", Calories: 185  },
                        {Name: "ผัดวุ้นเส้นใส่ไข่	1 จาน	", Calories: 265  },
                        {Name: "ผัดหมี่ซั่ว	1 จาน	", Calories: 395  },
                        {Name: "เผือกทอด	1 ชิ้น	", Calories: 99  },
                        {Name: "ฝรั่ง	1 ผล	", Calories: 174  },
                        {Name: "ฝอยทอง	1 แพ	", Calories: 146  },
                        {Name: "เฝอ	1 ถ้วย	", Calories: 240  },
                        {Name: "พอร์คชอปทอดผักผัดเนย	1 จาน	", Calories: 545  },
                        {Name: "พะแนงไก่	1 ถ้วย	", Calories: 230  },
                        {Name: "พะโล้	1 ถ้วย	", Calories: 210  },
                        {Name: "พุทรา	1 ลูก	", Calories: 20  },
                        {Name: "ฟักตุ๋นไก่มะนาวดอง	1 ถ้วย	", Calories: 125  },
                        {Name: "ฟักทองแกงบวช	1 ถ้วยเล็ก	", Calories: 165  },
                        {Name: "ฟักทองแกงบวด	1 ถ้วย	", Calories: 185  },
                        {Name: "มะกอกฝรั่ง	1 ผล	", Calories: 20  },
                        {Name: "มะขามหวาน	1 ผล	", Calories: 20  },
                        {Name: "มะปรางสุก	1 ผล	", Calories: 20  },
                        {Name: "มะเฟือง	1 ผล	", Calories: 120  },
                        {Name: "มะไฟ	1 ผล	", Calories: 4  },
                        {Name: "มะม่วงเขียวเสวย	1 ผล	", Calories: 120  },
                        {Name: "มะม่วงดิบ	1 ลูก	", Calories: 110  },
                        {Name: "มะม่วงน้ำดอกไม้	1 ชิ้น	", Calories: 15  },
                        {Name: "มะม่วงสุก	1 ลูก	", Calories: 98  },
                        {Name: "มะม่วงอกร่องสุก	1 ชิ้น	", Calories: 15  },
                        {Name: "มะยม	1 เม็ด	", Calories: 4  },
                        {Name: "มะละกอ	1 ชิ้น	", Calories: 8  },
                        {Name: "มักกะโรนีขี้เมาไก่	1 จาน	", Calories: 520  },
                        {Name: "มักกะโรนีผัดกุ้ง	1 จาน	", Calories: 420  },
                        {Name: "มังคุด	1 ผล	", Calories: 13  },
                        {Name: "มันแกงบวช	1 ถ้วยเล็ก	", Calories: 184  },
                        {Name: "มันทอด	1 ชิ้น	", Calories: 124  },
                        {Name: "มั่นฝรั่งทอด (เฟร้นฟราย)	1 ชิ้น	", Calories: 20  },
                        {Name: "เม็ดขนุน (ขนมไทย)	1 เม็ด	", Calories: 35  },
                        {Name: "เมล็ดมะม่วงหิมพานต์ทอด	1 ชิ้น	", Calories: 28  },
                        {Name: "เมี่ยงก๋วยเตี๋ยว	1 คำ	", Calories: 20  },
                        {Name: "เมี่ยงคำ	1 คำ	", Calories: 30  },
                        {Name: "แม่โขง	1 cc	", Calories: 1  },
                        {Name: "ยากิโซบะ	1 จาน	", Calories: 400  },
                        {Name: "ยำกุนเชียง	1 จาน	", Calories: 220  },
                        {Name: "ยำขนมจีน	1 จาน	", Calories: 220  },
                        {Name: "ยำไข่ต้ม	1 ฟอง	", Calories: 105  },
                        {Name: "ยำไข่ต้มทรงเครื่อง	1 จาน	", Calories: 188  },
                        {Name: "ยำถั่วพู	1 จาน	", Calories: 185  },
                        {Name: "ยำเนื้อย่าง	1 จาน	", Calories: 165  },
                        {Name: "ยำปลากระป๋อง	1 จาน	", Calories: 55  },
                        {Name: "ยำปลาดุกฟู	1 จาน	", Calories: 275  },
                        {Name: "ยำปลาหมึกย่าง	1 จาน	", Calories: 99  },
                        {Name: "ยำผักกะเฉด	1 จาน	", Calories: 115  },
                        {Name: "ยำผักกาดดอง	1 จาน	", Calories: 30  },
                        {Name: "ยำผักบุ้งทอดกรอบ	1 จาน	", Calories: 310  },
                        {Name: "ยำมะเขือยาว	1 จาน	", Calories: 35  },
                        {Name: "ยำมะม่วงทะเล	1 จาน	", Calories: 136  },
                        {Name: "ยำมาม่า	1 จาน	", Calories: 215  },
                        {Name: "ยำแมงกระพรุน	1 จาน	", Calories: 105  },
                        {Name: "ยำรวมมิตรทะเล	1 จาน	", Calories: 132  },
                        {Name: "ยำวุ้นเส้น	1 จาน	", Calories: 120  },
                        {Name: "ยำไส้กรอก	1 จาน	", Calories: 110  },
                        {Name: "ยำหนังหมู	1 จาน	", Calories: 220  },
                        {Name: "ยำหมูย่าง	1 จาน	", Calories: 165  },
                        {Name: "ยำหอยแมลงภู่	1 จาน	", Calories: 60  },
                        {Name: "เย็นตาโฟ	1 ชาม	", Calories: 290  },
                        {Name: "ระกำ	1 ผล	", Calories: 8  },
                        {Name: "ราดหน้าบะหมี่กรอบ	1 จาน	", Calories: 515  },
                        {Name: "ราดหน้าบะหมี่กรอบไก่	1 จาน	", Calories: 660  },
                        {Name: "ราดหน้าปลากระพง	1 จาน	", Calories: 435  },
                        {Name: "ราดหน้าเส้นใหญ่หมู	1 จาน	", Calories: 405  },
                        {Name: "ราดหน้าหมูหมี่กรอบ	1 จาน	", Calories: 690  },
                        {Name: "รูทเบียร์	1 แก้ว	", Calories: 105  },
                        {Name: "โรตี ใส่นมข้นและน้ำตาล	1 ชิ้น	", Calories: 192  },
                        {Name: "โรตีแกงเนื้อ,หมู	1 ชุด	", Calories: 675  },
                        {Name: "ลองกอง	1 ลูก	", Calories: 6  },
                        {Name: "ลอดช่องน้ำกะทิ	1 ถ้วย	", Calories: 210  },
                        {Name: "ลอดช่องสิงคโปร์	1 ถ้วย	", Calories: 215  },
                        {Name: "ละมุด	1 ผล	", Calories: 120  },
                        {Name: "ลางสาด	1 ผล	", Calories: 6  },
                        {Name: "ลาบไก่	1 จาน	", Calories: 125  },
                        {Name: "ลาบเนื้อ	1 จาน	", Calories: 119  },
                        {Name: "ลาบปลา	1 จาน	", Calories: 94  },
                        {Name: "ลาบหมู	1 จาน	", Calories: 119  },
                        {Name: "ลำไย	1 เม็ด	", Calories: 8  },
                        {Name: "ลำไยแห้ง	1 เม็ด	", Calories: 9  },
                        {Name: "ลิ้นจี่	1 ลูก	", Calories: 17  },
                        {Name: "ลูกเกด	1 เม็ด	", Calories: 4  },
                        {Name: "ลูกชิ้นไก่	1 ลูก	", Calories: 6  },
                        {Name: "ลูกชิ้นทอด	1 ลูก	", Calories: 35  },
                        {Name: "ลูกชิ้นเนื้อวัว	1 ลูก	", Calories: 8  },
                        {Name: "ลูกชิ้นปลา	1 ลูก	", Calories: 4  },
                        {Name: "ลูกชุบ	1 ชิ้น	", Calories: 57  },
                        {Name: "ลูกตาลอ่อน	1 ผล	", Calories: 120  },
                        {Name: "ลูกพลับ	1 ผล	", Calories: 120  },
                        {Name: "วอดก้า	1 cc	", Calories: 2  },
                        {Name: "วิสกี้	1 cc	", Calories: 2  },
                        {Name: "วุ้นเส้นต้มยำ	1 จาน	", Calories: 245  },
                        {Name: "วุ้นเส้นผัดไทยกุ้งสด	1 จาน	", Calories: 520  },
                        {Name: "ไวตามิลค์	1 ขวด	", Calories: 150  },
                        {Name: "ไวน์เชอรี่	1 cc	", Calories: 1  },
                        {Name: "สตรอวเบอร์รี่	1 ผล	", Calories: 60  },
                        {Name: "สเต็กไก่ทอด + มันบด	1 จาน	", Calories: 615  },
                        {Name: "สเต็กปลาย่าง	1 จาน	", Calories: 260  },
                        {Name: "สเต็กหมู + ผักสลัด	1 จาน	", Calories: 505  },
                        {Name: "สปาเกตตี้กะเพรากุ้ง	1 จาน	", Calories: 485  },
                        {Name: "สปาเก็ตตี้ไก่อบ	1 จาน	", Calories: 430  },
                        {Name: "ส้มเขียวหวาน	1 ลูก	", Calories: 32  },
                        {Name: "ส้มเช้ง	1 ผล	", Calories: 60  },
                        {Name: "ส้มตำ ไม่ใส่ถั่ว	1 จาน	", Calories: 80  },
                        {Name: "ส้มตำไทย ไม่ใส่ถั่ว	1 จาน	", Calories: 55  },
                        {Name: "ส้มตำปู ไม่ใส่ถั่ว	1 จาน	", Calories: 35  },
                        {Name: "ส้มตำปูไทย ไม่ใส่ถั่ว	1 จาน	", Calories: 118  },
                        {Name: "ส้มแป้น	1 กิโลกรัม	", Calories: 340  },
                        {Name: "ส้มโอ	1 กรีบ	", Calories: 60  },
                        {Name: "สละหวาน	1 ผล	", Calories: 60  },
                        {Name: "สลัดกุ้ง	1 จาน	", Calories: 92  },
                        {Name: "สลัดกุ้งน้ำใส	1 จาน	", Calories: 92  },
                        {Name: "สลัดไก่	1 จาน	", Calories: 97  },
                        {Name: "สลัดแขก	1 จาน	", Calories: 230  },
                        {Name: "สลัดไข่	1 จาน	", Calories: 123  },
                        {Name: "สลัดเนื้อสันในทอด	1 จาน	", Calories: 490  },
                        {Name: "สลัดปลาทูน่า	1 จาน	", Calories: 122  },
                        {Name: "สับปรด	1 ชิ้นเล็ก	", Calories: 8  },
                        {Name: "สัมปะนี	1 ชิ้น	", Calories: 21  },
                        {Name: "สาคูไส้หมู	1 ลูก	", Calories: 51  },
                        {Name: "สาลี่	1 ผล	", Calories: 116  },
                        {Name: "สำลีหอม	1 ผล	", Calories: 60  },
                        {Name: "สุกี้กุ้ง ไม่ใส่วุ้นเส้น	1 ถ้วย	", Calories: 200  },
                        {Name: "สุกี้ไก่ ไม่ใส่วุ้นเส้น	1 ถ้วย	", Calories: 200  },
                        {Name: "สุกี้น้ำไก่	1 ชาม	", Calories: 345  },
                        {Name: "สุกี้หมู ไม่ใส่วุ้นเส้น	1 ถ้วย	", Calories: 200  },
                        {Name: "สุกี้แห้งทะเล	1 ชาม	", Calories: 280  },
                        {Name: "เส้นก๋วยเตี๋ยวผัดขี้เมา	1 จาน	", Calories: 605  },
                        {Name: "เส้นจันท์ผัดปู	1 จาน	", Calories: 575  },
                        {Name: "เส้นหมี่ลูกชิ้นน้ำใส	1 ชาม	", Calories: 225  },
                        {Name: "เส้นหมี่ลูกชิ้นหมูแห้ง	1 ชาม	", Calories: 430  },
                        {Name: "เส้นใหญ่ผัดซีอิ๊วใส่ไข่	1 จาน	", Calories: 520  },
                        {Name: "ไส้กรอกเนื้อลูกวัวอบสลัดผัก	1 จาน	", Calories: 465  },
                        {Name: "ไส้กรอกอีสาน	1 ลูก	", Calories: 90  },
                        {Name: "ไส้อั่ว	1 คำ	", Calories: 60  },
                        {Name: "หน่อไม้ผัดไข่	1 จาน	", Calories: 200  },
                        {Name: "หมี่กรอบราดหน้าหมู	1 จาน	", Calories: 690  },
                        {Name: "หมี่กะทิ	1 จาน	", Calories: 405  },
                        {Name: "หมี่ซั่วผัด	1 จาน	", Calories: 395  },
                        {Name: "หมูกรอบ	1 จาน	", Calories: 560  },
                        {Name: "หมูกะทะ	1 ชุด	", Calories: 375  },
                        {Name: "หมูคลุกเกร็ดขนมปังทอดซอส	1 ชุด	", Calories: 645  },
                        {Name: "หมูจุ่ม	1 ชุด	", Calories: 375  },
                        {Name: "หมูทอดเนยสลัดน้ำใส	1 จาน	", Calories: 635  },
                        {Name: "หมูน้ำตก	1 จาน	", Calories: 165  },
                        {Name: "หมูบด	1 ช้อนโต๊ะ	", Calories: 50  },
                        {Name: "หมูปิ้ง	1 ไม้	", Calories: 125  },
                        {Name: "หมูผัดขิง	1 จาน	", Calories: 275  },
                        {Name: "หมูแผ่น	1 แผ่นกลาง	", Calories: 120  },
                        {Name: "หมูฝอย	1 ช้อนโต๊ะ	", Calories: 68  },
                        {Name: "หมูยอชุบแป้งทอด	1 ชิ้น	", Calories: 125  },
                        {Name: "หมูย่างเกาหลี	1 ชุด	", Calories: 375  },
                        {Name: "หมูสะเต๊ะ	1 ไม้	", Calories: 115  },
                        {Name: "หมูหยอง	1 ช้อนโต๊ะ	", Calories: 38  },
                        {Name: "หลนปูเค็ม	1 ถ้วย	", Calories: 205  },
                        {Name: "หอยแมลงภู่ทอด	1 จาน	", Calories: 605  },
                        {Name: "หอยแมลงภู่อบหม้อดิน	1 ตัว	", Calories: 17  },
                        {Name: "เห็ดผัดน้ำมันหอย	1 จาน	", Calories: 185  },
                        {Name: "แหนมสด	1 จาน	", Calories: 175  },
                        {Name: "อกไก่ย่าง	1 ชิ้น	", Calories: 110  },
                        {Name: "อกไก่อบ	1 ชิ้น	", Calories: 169  },
                        {Name: "องุ่น	1 เม็ด	", Calories: 16  },
                        {Name: "องุ่นเปรียว	1 เม็ด	", Calories: 3  },
                        {Name: "องุ่นหวาน	1 เม็ด	", Calories: 4  },
                        {Name: "อ้อยควั่น	1 ชิ้น	", Calories: 12  },
                        {Name: "แอปเปิ้ล	1 ลูก	", Calories: 42  },
                        {Name: "โอวัลติน	1 แก้ว	", Calories: 220  },
                        {Name: "ฮะเก๋า	1 ลูกเล็ก	", Calories: 115  },
                        {Name: "ขนมถ้วย	1 ถ้วย	", Calories: 133  },
                        {Name: "กระทงทองไส้ข้าวโพด	1 ชิ้น	", Calories: 72  },
                        {Name: "กระทงทองไส้ไก่	1 ชิ้น	", Calories: 93  },
                        {Name: "กระยาสารท	1 ชิ้นกลาง	", Calories: 210  },
                        {Name: "กล้วยคลุกมะพร้าว	1 ถ้วยเล็ก	", Calories: 100  },
                        {Name: "ขนมชั้น	1 ชิ้น	", Calories: 92  },
                        {Name: "ขนมต้มขาว	1 ลูก	", Calories: 41  },
                        {Name: "ขนมปลากริมไข่เต่า	1 ถ้วย	", Calories: 250  },
                        {Name: "ขนมปังกระเทียม	1 ชิ้น	", Calories: 85  },
                        {Name: "ขนมปังขาไก่	1 ชิ้น	", Calories: 65  },
                        {Name: "ขนมปังปอนด์	1 แผ่น	", Calories: 80  },
                        {Name: "ขนมปังมะพร้าว	1 ชิ้น	", Calories: 235  },
                        {Name: "ขนมปังสังขยา	1 ชิ้น	", Calories: 230  },
                        {Name: "ขนมปังอบกรอบ	1 แผ่นเล็ก	", Calories: 20  },
                        {Name: "ขนมปังไส้กรอก	1 ชิ้น	", Calories: 130  },
                        {Name: "ขนมปังไส้หมูหยอง	1 ชิ้น	", Calories: 185  },
                        {Name: "ขนมหม้อแกง	1 ชิ้น	", Calories: 179  },
                        {Name: "ขนมไหว้พระจันทร์ไส้ทุเรียนกวน	1 ชิ้น	", Calories: 340  },
                        {Name: "ขนมไหว้พระจันทร์ไส้ลูกบัวไข่เค็ม	1 ชิ้น	", Calories: 375  },
                        {Name: "ข้าวกุ้งทอดกระเทียมพริกไทย	1 จาน	", Calories: 495  },
                        {Name: "ข้าวเหนียวหน้ากุ้ง	1 ห่อ	", Calories: 179  },
                        {Name: "ข้าวเหนียวสังขยา	1 ห่อ	", Calories: 370  },
                        {Name: "ครีมเทียม	1 ช้อนชา	", Calories: 45  },
                        {Name: "ครีมโรล	1 ชิ้น	", Calories: 360  },
                        {Name: "คอร์นเฟลค	1 ถ้วยตวง	", Calories: 110  },
                        {Name: "คุ้กกี้ข้าวโอ๊ต	1 ชิ้น	", Calories: 75  },
                        {Name: "คุ้กกี้ชาเขียว	1 ชิ้น	", Calories: 75  },
                        {Name: "คุ้กกี้ช็อคโกแลตชิพ	1 ชิ้น	", Calories: 215  },
                        {Name: "คุ้กกี้สิงคโปร์	1 ชิ้น	", Calories: 95  },
                        {Name: "คุ้กกี้เนย	1 ชิ้น	", Calories: 105  },
                        {Name: "คุ้กกี้ไส้สับปะรด	1 ชิ้น	", Calories: 190  },
                        {Name: "ชาดำเย็น	1 แก้ว	", Calories: 110  },
                        {Name: "ชามะนาว	1 แก้ว	", Calories: 100  },
                        {Name: "ชาร้อน	1 แก้ว	", Calories: 55  },
                        {Name: "ชาเย็น	1 แก้ว	", Calories: 100  },
                        {Name: "ช็อคโกแลตร้อน	1 แก้ว	", Calories: 120  },
                        {Name: "ถั่วลิสงแผ่นทอด	1 แผ่น	", Calories: 150  },
                        {Name: "ถั่วลิสงต้ม	1 ช้อนโต๊ะ	", Calories: 45  },
                        {Name: "ถั่วเขียวต้มน้ำตาล	1 ถ้วยเล็ก	", Calories: 160  },
                        {Name: "ทองหยิบ	1 ดอก	", Calories: 105  },
                        {Name: "ทุเรียนกวน	1 ช้อนโต๊ะ	", Calories: 115  },
                        {Name: "น้ำนมข้าวโพด	1 แก้ว	", Calories: 80  },
                        {Name: "น้ำตาลทราย	1 ช้อนชา	", Calories: 20  },
                        {Name: "น้ำฝรั่ง	1 กล่อง	", Calories: 100  },
                        {Name: "บราวนี่	1 ชิ้น	", Calories: 340  },
                        {Name: "น้ำใบเตย	1 แก้ว	", Calories: 120  },
                        {Name: "น้ำใบบัวบก	1 แก้ว	", Calories: 120  },
                        {Name: "พายกรอบ	1 ชิ้น	", Calories: 118  },
                        {Name: "พายชีสบูลเบอร์รี่	1 ชิ้น	", Calories: 350  },
                        {Name: "พายทูน่า	1 ชิ้น	", Calories: 280  },
                        {Name: "พิซซ่าขอบไส้กรอกชีส	1 ชิ้น	", Calories: 340  },
                        {Name: "พิซซ่าทะเล	1 ชิ้น	", Calories: 335  },
                        {Name: "พิซซ่าฮาวายเอี้ยน	1 ชิ้น	", Calories: 345 },
                        {Name: "พิซซ่าไส้กรอก	1 ชิ้น	", Calories: 290  },
                        {Name: "ฟักทองเชื่อม	1 จาน	", Calories: 167  },
                        {Name: "มะกอกทรงเครื่อง	1 ผล	", Calories: 33  },
                        {Name: "มะขามหวาน	1 ฝัก	", Calories: 30  },
                        {Name: "มะม่วงอกร่องสุก	1 ชิ้น	", Calories: 15  },
                        {Name: "มันฝรั่งแผ่น	1 ชิ้น	", Calories: 13  },
                        {Name: "มันเทศเชื่อม	1 ถ้วยเล็ก	", Calories: 230  },
                        {Name: "มันแกงบวด	1 ถ้วยเล็ก	", Calories: 184  },
                        {Name: "มาการีน	1 ช้อนชา	", Calories: 45  },
                        {Name: "รวมมิตร	1 ถ้วยเล็ก	", Calories: 230  },
                        {Name: "ลูกชิ้นปิ้ง	1 ไม้	", Calories: 165  },
                        {Name: "ลูกตาลลอยแก้ว	1 ถ้วย	", Calories: 180  },
                        {Name: "ลูกเกด	1 เม็ด	", Calories: 4  },
                        {Name: "วุ้นมะพร้าวอ่อน	1 ชิ้น	", Calories: 80  },
                        {Name: "สังขยา	1 ชิ้นเล็ก	", Calories: 204  },
                        {Name: "สังขยาฟักทอง	1 ชิ้นเล็ก	", Calories: 288  },
                        {Name: "สังขยาเผือก	1 ชิ้นเล็ก	", Calories: 222  },
                        {Name: "เกี๊ยวกรอบ	1 ชิ้น	", Calories: 78  },
                        {Name: "เค้กกล้วยหอม	1 ชิ้น	", Calories: 370  },
                        {Name: "เค้กช็อคโกแลต	1 ชิ้น	", Calories: 275  },
                        {Name: "เค้กเนย	1 ชิ้น	", Calories: 255  },
                        {Name: "เค้กใบเตย	1 ชิ้น	", Calories: 250  },
                        {Name: "เต้าหู้เหลือง	1 ชิ้น	", Calories: 90  },
                        {Name: "แซนวิชแฮมชีส	1 คู่	", Calories: 290  },
                        {Name: "แซนวิชทูน่า	1 คู่	", Calories: 180  },
                        {Name: "แซนวิชไก่	1 คู่	", Calories: 240  },
                        {Name: "แยมโรล	1 ชิ้น	", Calories: 310  },
                        {Name: "แฮมเบอร์เกอร์ไก่ชีส	1 ชิ้น	", Calories: 280  },
                        {Name: "แฮมเบอร์เกอร์หมู	1 ชิ้น	", Calories: 245  },
                        {Name: "โดนัท	1 ชิ้น	", Calories: 270  },
                        {Name: "โรตีสายไหม	1 ชิ้น	", Calories: 145  },
                        {Name: "ไอศกรีมกะทิ	1 ก้อน	", Calories: 108  },
                        {Name: "ไอศกรีมกาแฟ	1 ก้อน	", Calories: 142  },
                        {Name: "ไอศกรีมชอกโกแล็ต	1 ก้อน	", Calories: 110  },
                        {Name: "ไอศกรีมวนิลลา	1 ก้อน	", Calories: 140  },
                        {Name: "ไอศกรีมสตรอเบอรี่	1 ก้อน	", Calories: 110  },
                        {Name: "ไอศกรีมเรซิน	1 ก้อน	", Calories: 264 }
                       ];

        function priceFormatter(cell, row)
        {
            return '<i class="glyphicon glyphicon-flash"></i> ' + cell;
        }

        const options = {
            onRowDoubleClick: this.OnInsertRow,
            clearSearch: true,
        };

        const options_eat = {
            afterInsertRow: this.OnInsertRow,
            afterDeleteRow: this.OnAfterDeleteRow,
            showFooter: true,
        }

        const selectRow = {
            mode: 'radio',
            clickToSelect: true,
            hideSelectColumn: true,
            bgColor: "#ccc",
        };

        const selectRowProp = {
            mode: 'checkbox',
            clickToSelect: true,
            bgColor: "#ccc",
        };

        let summary = 0;
        var list = this.state.listEat.slice();

        for(var i = 0; i < list.length; i++)
        {
            try
            {
                summary += parseInt(list[i].Calories);
            }
            catch(err){}
        }

        return (
            <div className="App-Cal anim_all">
                <div className="row">

                    {/*Table*/}
                    <div className="col-md-7 is-background">
                        <BootstrapTable data={products} hover={false} selectRow={selectRow} search={true} options={options} pagination trClassName="my-table" headerStyle={{background: '#fff', color: '#000'}}>
                            <TableHeaderColumn dataField="Name" isKey={true} dataSort={true}>Name - double click to select menu</TableHeaderColumn>
                            <TableHeaderColumn dataField="Calories" width="100" dataSort={true} dataFormat={priceFormatter}>Calories</TableHeaderColumn>
                        </BootstrapTable>
                    </div>

                    {/*Eat*/}
                    <div className="col-md-5">
                        <BootstrapTable data={this.state.listEat} insertRow={true} deleteRow={ true } selectRow={ selectRowProp } options={options_eat} trClassName="my-table" headerStyle={{background: '#fff', color: '#000'}}>
                            <TableHeaderColumn dataField="id" isKey={true} autoValue={true} hidden={true}>id</TableHeaderColumn>
                            <TableHeaderColumn dataField="Name" dataSort={true}>Name</TableHeaderColumn>
                            <TableHeaderColumn dataField="Calories" dataSort={true}>Calories ({summary})</TableHeaderColumn>
                        </BootstrapTable>
                    </div>
                </div>
            </div>
        );
    }
}
